# Site settings
title: Which UI? Jekyll Experiment
email: jacob.walton@which.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jacobwalton.github.io/wui" # the base hostname & protocol for your site
twitter_username: cobacious
github_username:  jacobwalton

# Build settings
markdown: kramdown
